export enum TaskActionTypes {
    SET_TASKS = 'SET_TASKS',
    SET_TASK_NAME = 'SET_TASK_NAME',
    SET_TEAM_MEMBERS = 'SET_TEAM_MEMBERS',
    SET_IS_FETCHING_TEAM_MEMBERS = 'SET_IS_FETCHING_TEAM_MEMBERS',
}
